server:
  port: ${8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: agenda
          uri: lb://agenda
          predicates:
            - Path=/agenda/**
        - id: funcionario
          uri: lb://funcionario
          predicates:
            - Path=/funcionario/**
        - id: sala
          uri: lb://sala
          predicates:
            - Path=/sala/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
